### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [kberezovsky/Terse-STL-algorithms#1]
Would you like to [replace any double quotes](https://github.com/kberezovsky/Terse-STL-algorithms/blob/75c261b5c251e9e47697076a8423a8b99b4f2da1/terse/algorithm.hpp#L10) by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename)?

**Comment by kberezovsky** [comment]
From my point of view, double quotes are appropriate here. I want to use the exact file from the current library directory. I see no sense to search other directories.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html) from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf) in the standard specification for the programming language "C++".

```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```
- How do you think about to avoid "a duplicated file search" here?
- Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html) for header files of your software?

**Comment by kberezovsky** [comment]
- Yes, the quotes can't prevent the search. But they may express an intention to use the local file.  
- As far as I can understand the [description of -iquote](https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html), -iquote is very like to -I . The only difference -iquote has effect for "file.h" only. But my headers are fine without these additional search paths.

**Comment by elfring** [comment]
There are different opinions about the handling of the involved implementation-defined behaviour.
- Will header files be also searched outside the specified include directories if double quotes are used for the discussed preprocessor statement?
- Is there a speed difference measurable if a file is not found there and the search will be retried with "the angle brackets inclusion method"?
